export IMAGE_NAME="nginx-naxsi-amplify-wordpress"
export CONTAINER_NAME="nginx-naxsi-amplify-wordpress"
export SITE_NAME="quranerkotha.com"
export EMAIL="omaralzabir@gmail.com"
export HOST_IP="127.0.0.1"
export HOST_PORT="53001"
export SERVER_NAMES="quranerkotha.com"
